// Converts an AmneziaWG configuration (.conf) into a mihomo configuration.
// Self-contained so the binary needs no external generator.
package awgconf

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"
	"net"
	"os"
	"regexp"
	"strings"

	"dpiswitch/internal/ctl"
	"dpiswitch/internal/paths"
	"dpiswitch/internal/presets"
	"dpiswitch/internal/probe"
)

type Section map[string]string

type Conf struct {
	Interface Section
	Peer      Section
}

func Parse(text string) (*Conf, error) {
	c := &Conf{Interface: Section{}, Peer: Section{}}
	var cur Section
	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		if strings.HasPrefix(line, "[") {
			switch strings.ToLower(strings.Trim(line, "[]")) {
			case "interface":
				cur = c.Interface
			case "peer":
				cur = c.Peer
			default:
				cur = nil
			}
			continue
		}
		if cur == nil {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		cur[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	if c.Interface["PrivateKey"] == "" {
		return nil, fmt.Errorf("the config has no PrivateKey")
	}
	if c.Peer["Endpoint"] == "" {
		return nil, fmt.Errorf("the config has no Endpoint")
	}
	return c, nil
}

func ParseFile(path string) (*Conf, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return Parse(string(b))
}

var secretRe = regexp.MustCompile(`(?m)^secret:\s*'([^']+)'`)

// the secret is reused: the tray and the controller rely on it,
// and a new one on every generation would silently break their API access
func keepSecret(existing string) string {
	if b, err := os.ReadFile(existing); err == nil {
		if m := secretRe.FindSubmatch(b); m != nil {
			return string(m[1])
		}
	}
	buf := make([]byte, 8)
	_, _ = rand.Read(buf)
	return hex.EncodeToString(buf)
}

func split(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func quoteList(items []string) string {
	q := make([]string, 0, len(items))
	for _, i := range items {
		q = append(q, "'"+i+"'")
	}
	return "[" + strings.Join(q, ", ") + "]"
}

// DNS: resolvers from the [Interface] section
func (c *Conf) DNS() []string {
	out := split(c.Interface["DNS"])
	if out == nil {
		out = []string{}
	}
	return out
}

// Render builds the mihomo configuration from a parsed .conf.
func (c *Conf) Render() (string, error) {
	host, _, err := net.SplitHostPort(c.Peer["Endpoint"])
	if err != nil {
		return "", fmt.Errorf("cannot parse Endpoint: %w", err)
	}

	if _, _, err := c.addrs(); err != nil {
		return "", err
	}
	// the second tunnel, if loaded; a broken second source
	// must not break the first one, so the error only goes to the log
	var c2 *Conf
	if _, err := os.Stat(paths.SourceConf2()); err == nil {
		if cc, err := ParseFile(paths.SourceConf2()); err != nil {
			log.Printf("second tunnel not attached: %v", err)
		} else if _, _, err := cc.addrs(); err != nil {
			log.Printf("second tunnel not attached: %v", err)
		} else {
			c2 = cc
		}
	}

	dns := split(c.Interface["DNS"])
	set := ctl.LoadSettings(paths.Settings())
	// tunnel resolvers: from settings, otherwise from the .conf
	tunDNS := dns
	if len(set.TunnelDNS) > 0 {
		tunDNS = set.TunnelDNS
	}
	directDNS := set.DirectDNS
	bootstrap := bootstrapDNS(directDNS)
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# generated by dpiswitch from source.conf -- manual edits are pointless,")
	w("# the file is rewritten whenever the config is rebuilt.")
	w("# provider paths are relative: mihomo forbids paths outside")
	w("# its home directory, so the core runs with -d <data directory>")
	w("mixed-port: 7890")
	w("allow-lan: false")
	w("mode: rule")
	w("log-level: info")
	w("ipv6: true")
	w("unified-delay: true")
	w("tcp-concurrent: true")
	w("# processes are looked up lazily -- only when a process rule is reached;")
	w("# with an empty exclusion list this costs nothing")
	w("find-process-mode: strict")
	w("external-controller: 127.0.0.1:9090")
	w("secret: '%s'", keepSecret(paths.Config()))
	w("")
	w("# a dedicated listener for the prober: bypasses rules, always direct.")
	w("# the only way to give the prober a direct path while TUN")
	w("# captures all other traffic.")
	w("listeners:")
	w("  - name: probe-direct")
	w("    type: mixed")
	w("    listen: 127.0.0.1")
	w("    port: 7892")
	w("    proxy: DIRECT")
	w("  # the tunnel probe listener is bound to awg itself, NOT to the group:")
	w("  # if the group fell back to DIRECT both probes would go direct and")
	w("  # the detector would call everything clean -- the costliest mistake")
	w("  - name: probe-tunnel")
	w("    type: mixed")
	w("    listen: 127.0.0.1")
	w("    port: 7891")
	w("    proxy: awg")
	w("")
	w("tun:")
	w("  enable: true")
	w("  stack: gvisor")
	if set.IPv6 {
		// IPv6 inside the tunnel: the system needs an IPv6 address and route,
		// otherwise programs don't even try IPv6
		w("  inet6-address:")
		w("    - 'fdfe:dcba:9876::1/126'")
	}
	w("  auto-route: true")
	w("  auto-detect-interface: true")
	w("  dns-hijack:")
	w("    - any:53")
	w("")
	w("# recovers the domain from the ClientHello for software that")
	w("# resolves around us (browsers with their own DoH)")
	w("sniffer:")
	w("  enable: true")
	w("  override-destination: true")
	w("  skip-src-address:")
	w("    - 127.0.0.1/32")
	w("  sniff:")
	w("    TLS:")
	w("      ports: [443, 8443]")
	w("    QUIC:")
	w("      ports: [443]")
	w("    HTTP:")
	w("      ports: [80, 8080, 8880]")
	w("      override-destination: false")
	w("")
	w("dns:")
	w("  enable: true")
	w("  listen: 127.0.0.1:1053")
	w("  ipv6: true")
	w("  enhanced-mode: fake-ip")
	w("  fake-ip-range: 198.18.0.1/16")
	if set.IPv6 {
		// AAAA queries get a fake address too: the connection arrives
		// with the domain, and "direct / tunnel" rules work just as for IPv4.
		//
		// The range is 2001:2::/48 (reserved for benchmarking, RFC 5180),
		// NOT ULA fc00::/7. Chrome treats ULA as a local network and, under
		// Local Network Access rules, silently blocks requests from public
		// pages to such addresses (ERR_FAILED, the request never hits the network).
		// With ULA, iframes, WebSockets and navigation broke: Telegram Web
		// hung on "Waiting for network", embedded video players did not load.
		// Chrome does not treat 198.18.0.0/15 as local for IPv4 -- so the same
		// kind of benchmarking range is used for IPv6.
		w("  fake-ip-range6: '2001:2::/48'")
	}
	w("  fake-ip-filter:")
	for _, z := range localPatterns() {
		w("    - '%s'", z)
	}
	if net.ParseIP(host) == nil {
		w("    - '%s'", host)
	}
	if c2 != nil {
		if h2, _, err := net.SplitHostPort(c2.Peer["Endpoint"]); err == nil && net.ParseIP(h2) == nil {
			w("    - '%s'", h2)
		}
	}
	// Two resolvers for two paths.
	// The tunnel resolves by itself, with its DNS inside the tunnel (remote-dns-resolve
	// on awg): the node is chosen for the VPS that traffic will exit from.
	// The direct path uses direct-nameserver, reached directly: CDNs
	// hand out nodes for the user's ISP. The prober asks the same server,
	// so exactly the node traffic will use gets tested.
	// When the tunnel group falls back to DIRECT, names also resolve
	// via direct-nameserver -- they keep working without the tunnel.
	// No list mixes paths: the core queries the resolvers of a list
	// concurrently, and a mix would return answers from either one.
	w("  # resolves servers given by name; IPs only -- avoids chicken-and-egg")
	w("  default-nameserver:")
	for _, d := range bootstrap {
		w("    - '%s'", d)
	}
	w("  # everything else (fake-ip-filter, internal queries) -- the same direct DNS")
	w("  nameserver:")
	for _, d := range directDNS {
		w("    - '%s'", d)
	}
	w("  # local names go to the DNS the router hands out over DHCP: the remote")
	w("  # resolver has never heard of them, and the router answers for itself")
	w("  nameserver-policy:")
	w("    '%s':", strings.Join(localPatterns(), ","))
	w("      - 'dhcp://system'")
	w("      - 'system'")
	w("  direct-nameserver:")
	for _, d := range directDNS {
		w("    - '%s'", d)
	}
	w("  proxy-server-nameserver:")
	for _, d := range bootstrap {
		w("    - '%s'", d)
	}
	w("")
	w("# A fallback group. Without it a dead tunnel would mean no internet")
	w("# at all: every rule leads to awg, and awg does not answer.")
	w("# fallback checks the tunnel itself and, when it is down, sends traffic")
	w("# direct -- no protection at that moment, but connectivity remains.")
	w("proxy-groups:")
	w("  - name: tunnel")
	w("    type: fallback")
	w("    proxies:")
	w("      - awg")
	w("      - DIRECT")
	w("    url: 'http://cp.cloudflare.com/generate_204'")
	w("    interval: 30")
	// the first check runs as the core starts, when the WireGuard
	// handshake has not finished yet: DNS inside the tunnel is lost and retried
	// after ~5 s. With the default 5 s the check failed, the tunnel
	// was considered dead, and until the next check (30 s) the group sent
	// everything direct -- blocked sites included. Until the check completes
	// the tunnel counts as alive anyway, so the extra margin costs nothing
	w("    timeout: 15000")
	w("    lazy: false")
	w("")
	w("  # the second tunnel for presets and the custom list. If it is down,")
	w("  # traffic goes through the first tunnel; if both are down -- direct.")
	w("  # Without a second tunnel the group has no awg2, and presets are simply")
	w("  # pinned to the first tunnel.")
	w("  - name: tunnel2")
	w("    type: fallback")
	w("    proxies:")
	if c2 != nil {
		w("      - awg2")
	}
	w("      - awg")
	w("      - DIRECT")
	w("    url: 'http://cp.cloudflare.com/generate_204'")
	w("    interval: 30")
	w("    timeout: 15000")
	w("    lazy: false")
	w("")
	w("rule-providers:")
	w("  # second-tunnel presets: a disabled one is written empty, so")
	w("  # enabling and disabling need no core restart")
	for _, p := range presets.All {
		w("  preset-%s:", p.ID)
		w("    type: file")
		w("    behavior: classical")
		w("    format: text")
		w("    path: ./preset-%s.txt", p.ID)
	}
	w("  awg2-hosts:")
	w("    type: file")
	w("    behavior: domain")
	w("    format: text")
	w("    path: ./awg2-hosts.txt")
	w("  # user lists: the controller never touches or rewrites them")
	w("  force-direct-apps:")
	w("    type: file")
	w("    behavior: classical")
	w("    format: text")
	w("    path: ./force-direct-apps.txt")
	w("  force-tunnel:")
	w("    type: file")
	w("    behavior: domain")
	w("    format: text")
	w("    path: ./force-tunnel.txt")
	w("  force-direct:")
	w("    type: file")
	w("    behavior: domain")
	w("    format: text")
	w("    path: ./force-direct.txt")
	w("  # detector memory: rewritten by the controller")
	w("  direct-verified:")
	w("    type: file")
	w("    behavior: domain")
	w("    format: text")
	w("    path: ./direct-verified.txt")
	w("")
	w("proxies:")
	// a tunnel the check found IPv6 dead on keeps its address but resolves
	// IPv4 only -- otherwise every IPv6-only host hangs until its timeout
	tunV6 := ctl.LoadTunnelIPv6(paths.TunnelIPv6())
	c.writeProxy(w, "awg", tunDNS, set.IPv6, tunV6.Dead("awg"))
	if c2 != nil {
		// the second tunnel uses its own DNS from the .conf: names must be
		// resolved by the server that traffic will go through
		c2.writeProxy(w, "awg2", split(c2.Interface["DNS"]), set.IPv6, tunV6.Dead("awg2"))
	}
	w("")
	w("rules:")
	w("  # 1. the tunnel endpoints themselves -- always outside the tunnel, or it loops")
	writeEndpointRule(w, host)
	if c2 != nil {
		if h2, _, err := net.SplitHostPort(c2.Peer["Endpoint"]); err == nil {
			writeEndpointRule(w, h2)
		}
	}
	w("")
	w("  # 2. addressing INSIDE the tunnels. It lives in ULA space, which the next")
	w("  #    block sends direct -- including the DNS server inside the tunnel.")
	w("  #    These have to come first, or that DNS would be dialled on the local")
	w("  #    network, where nothing answers.")
	writeInsideRules(w, c, tunDNS, "tunnel")
	if c2 != nil {
		writeInsideRules(w, c2, split(c2.Interface["DNS"]), "tunnel2")
	}
	w("")
	w("  # 3. local networks -- the LAN, the router, printers, network shares.")
	w("  # Nothing here is reachable from the other end of a tunnel anyway.")
	w("  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve")
	w("  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve")
	w("  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve")
	w("  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve")
	w("  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve")
	w("  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve")
	w("  # multicast: mDNS 224.0.0.251 and SSDP 239.255.255.250 find the printers,")
	w("  # speakers and TVs on this network")
	w("  - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve")
	w("  - IP-CIDR,255.255.255.255/32,DIRECT,no-resolve")
	w("  - IP-CIDR,0.0.0.0/8,DIRECT,no-resolve")
	w("  - IP-CIDR6,::1/128,DIRECT,no-resolve")
	w("  - IP-CIDR6,fe80::/10,DIRECT,no-resolve")
	w("  - IP-CIDR6,ff00::/8,DIRECT,no-resolve")
	w("  - IP-CIDR6,fc00::/7,DIRECT,no-resolve")
	w("  # the same networks by name. An IP rule with no-resolve never fires for")
	w("  # a connection that carries a domain, and a request to the router does.")
	for _, s := range localSuffixes {
		w("  - DOMAIN-SUFFIX,%s,DIRECT", s)
	}
	for _, d := range localExact {
		w("  - DOMAIN,%s,DIRECT", d)
	}
	w("")
	w("  # 4. excluded programs: all their traffic bypasses the tunnel")
	w("  - RULE-SET,force-direct-apps,DIRECT")
	w("")
	w("  # 5. second tunnel: presets and custom list -- the detector leaves them alone")
	for _, p := range presets.All {
		w("  - RULE-SET,preset-%s,tunnel2", p.ID)
	}
	w("  - RULE-SET,awg2-hosts,tunnel2")
	w("")
	w("  # 6. user's always-tunnel list -- beats detector verdicts")
	w("  - RULE-SET,force-tunnel,tunnel")
	w("")
	w("  # 7. user's always-direct list")
	w("  - RULE-SET,force-direct,DIRECT")
	w("")
	w("  # 8. detector verdicts")
	w("  - RULE-SET,direct-verified,DIRECT")
	w("")
	w("  # 9. everything else goes to the first tunnel")
	w("  - MATCH,tunnel")
	return b.String(), nil
}

// addrs: interface addresses from [Interface] Address
func (c *Conf) addrs() (v4, v6 string, err error) {
	for _, a := range split(c.Interface["Address"]) {
		ip, _, _ := strings.Cut(a, "/")
		if strings.Contains(ip, ":") {
			v6 = ip
		} else {
			v4 = ip
		}
	}
	if v4 == "" {
		return "", "", fmt.Errorf("the config has no IPv4 address")
	}
	return v4, v6, nil
}

// Names that belong to this machine's own network. They are kept out of
// fake-ip, resolved by the DNS the router hands out over DHCP, and routed
// direct BY NAME: the IP rules below carry no-resolve, so they never fire for
// a connection that arrives with a domain -- and these always do.
var (
	// suffix and everything under it
	localSuffixes = []string{
		"lan", "local", "home", "home.arpa", "internal", "localdomain",
		// router names. Each is also a real public domain, so resolving them
		// through a tunnel would answer with the vendor's website instead of
		// the box in the next room.
		"miwifi.com", "fritz.box", "tplinkwifi.net", "routerlogin.net",
	}
	// exact names only: the rest of the domain is an ordinary website
	localExact = []string{"router.asus.com"}
)

// localPatterns: what fake-ip and the DNS policy match on.
func localPatterns() []string {
	out := make([]string, 0, len(localSuffixes)+len(localExact))
	for _, s := range localSuffixes {
		out = append(out, "+."+s)
	}
	return append(out, localExact...)
}

// writeInsideRules pins a tunnel's own ULA addressing to that tunnel. The
// local-network block below sends the whole of fc00::/7 direct, and the DNS
// server inside a tunnel lives in exactly that space.
func writeInsideRules(w func(string, ...any), c *Conf, dns []string, group string) {
	seen := map[string]bool{}
	emit := func(cidr string) {
		if cidr == "" || seen[cidr] {
			return
		}
		seen[cidr] = true
		w("  - IP-CIDR6,%s,%s,no-resolve", cidr, group)
	}
	if _, v6, err := c.addrs(); err == nil && v6 != "" {
		emit(prefix64(v6))
	}
	for _, d := range dns {
		ip := net.ParseIP(strings.Trim(d, "[]"))
		if ip == nil || ip.To4() != nil {
			continue
		}
		emit(prefix64(ip.String()))
	}
}

// prefix64: the /64 an address belongs to. Both ends of a tunnel and its DNS
// sit in the same /64, so one rule covers them.
func prefix64(addr string) string {
	ip := net.ParseIP(addr)
	if ip == nil || ip.To4() != nil {
		return ""
	}
	n := &net.IPNet{IP: ip.Mask(net.CIDRMask(64, 128)), Mask: net.CIDRMask(64, 128)}
	return n.String()
}

func writeEndpointRule(w func(string, ...any), host string) {
	if ip := net.ParseIP(host); ip != nil {
		if ip.To4() != nil {
			w("  - IP-CIDR,%s/32,DIRECT,no-resolve", host)
		} else {
			w("  - IP-CIDR6,%s/128,DIRECT,no-resolve", host)
		}
	} else {
		w("  - DOMAIN,%s,DIRECT", host)
	}
}

// writeProxy: an AmneziaWG outbound with the given name
func (c *Conf) writeProxy(w func(string, ...any), name string, tunDNS []string, ipv6, v6Dead bool) {
	host, port, _ := net.SplitHostPort(c.Peer["Endpoint"])
	v4, v6, _ := c.addrs()
	mtu := c.Interface["MTU"]
	if mtu == "" {
		mtu = "1420"
	}
	keepalive := c.Peer["PersistentKeepalive"]
	if keepalive == "" {
		keepalive = "0"
	}
	w("  - name: %s", name)
	w("    type: wireguard")
	w("    server: %s", host)
	w("    port: %s", port)
	w("    ip: %s", v4)
	if v6 != "" {
		w("    ipv6: %s", v6)
	}
	w("    private-key: '%s'", c.Interface["PrivateKey"])
	w("    public-key: '%s'", c.Peer["PublicKey"])
	if k := c.Peer["PresharedKey"]; k != "" {
		w("    pre-shared-key: '%s'", k)
	}
	allowed := split(c.Peer["AllowedIPs"])
	if len(allowed) == 0 {
		allowed = []string{"0.0.0.0/0", "::/0"}
	}
	w("    allowed-ips: %s", quoteList(allowed))
	w("    mtu: %s", mtu)
	// mihomo's own userspace TCP stack with BBR instead of the default gVisor
	// one. With gVisor the upload through the tunnel was capped at 5-20 Mbit/s
	// with an idle CPU and zero loss on the server -- a sender-side window
	// limit. Measured on the same tunnel: gVisor 7, mips 28, mips+cubic 108,
	// mips+bbr ~150 Mbit/s upload; download unchanged.
	w("    ip-stack:")
	w("      mode: mips")
	w("      congestion-controller: bbr")
	w("    persistent-keepalive: %s", keepalive)
	w("    udp: true")
	w("    remote-dns-resolve: true")
	if ipv6 && !v6Dead {
		// IPv4 first, IPv6 when a site has only IPv6. The address family a
		// program chose is not preserved with fake-ip: the core resolves the
		// domain again itself. With ipv6-prefer all tunnel traffic went over
		// IPv6, and a VPS may have several IPv6 addresses, some of which geo
		// databases place in another country -- sites saw the user hop countries.
		// A VPS typically has one IPv4, so the country stays consistent.
		w("    ip-version: ipv4-prefer")
	} else {
		// IPv6 turned off in the settings, or dead through this tunnel. Without this the outbound keeps
		// the core default, which is DualStack: the TUN hands out no IPv6
		// and no AAAA fake address, so nothing reaches the tunnel over IPv6,
		// but the core still resolves the domain itself on the other side and
		// may pick an AAAA there -- the very IPv6 egress the switch turns off.
		// The value is "ipv4", not "ipv4-only": an unknown one silently
		// unmarshals back to DualStack (constant/dns.go).
		w("    ip-version: ipv4")
	}
	if len(tunDNS) > 0 {
		w("    dns: %s", quoteList(tunDNS))
	}
	w("    amnezia-wg-option:")
	w("      version: 3")
	for _, k := range []string{"Jc", "Jmin", "Jmax", "S1", "S2", "S3", "S4"} {
		if v := c.Interface[k]; v != "" {
			w("      %s: %s", strings.ToLower(k), v)
		}
	}
	for _, k := range []string{"H1", "H2", "H3", "H4", "I1", "I2", "I3", "I4", "I5"} {
		if v := c.Interface[k]; v != "" {
			w("      %s: '%s'", strings.ToLower(k), v)
		}
	}
	strMap := [][2]string{
		{"HeaderProtectionKey", "header-protection-key"},
		{"ContentPaddingAddition", "content-padding-addition"},
		{"RekeyAfterTime", "rekey-after-time"},
		{"RekeyTimeout", "rekey-timeout"},
		{"RejectAfterTime", "reject-after-time"},
		{"KeepaliveTimeout", "keepalive-timeout"},
		{"MaxHandshakeAttempts", "max-handshake-attempts"},
	}
	for _, kv := range strMap {
		if v := c.Interface[kv[0]]; v != "" {
			w("      %s: '%s'", kv[1], v)
		}
	}
	for _, kv := range [][2]string{{"RandomTrailers", "random-trailers"}, {"DisableCookies", "disable-cookies"}} {
		switch strings.ToLower(c.Interface[kv[0]]) {
		case "on", "true", "1", "yes":
			w("      %s: true", kv[1])
		}
	}
}

// Regenerate rebuilds config.yaml from the saved source.
//
// The config is fully generated, so a new program version must
// deliver its changes (rules, providers) to an existing installation
// by itself, without reloading the .conf. The file is rewritten in
// place rather than replaced: this keeps the ACL that protects
// the private key. Returns true if anything changed.
func Regenerate() (bool, error) {
	c, err := ParseFile(paths.SourceConf())
	if err != nil {
		return false, err
	}
	out, err := c.Render()
	if err != nil {
		return false, err
	}
	if old, err := os.ReadFile(paths.Config()); err == nil && string(old) == out {
		return false, nil
	}
	f, err := os.OpenFile(paths.Config(), os.O_WRONLY|os.O_TRUNC, 0)
	if err != nil {
		return false, err
	}
	if _, err := f.WriteString(out); err != nil {
		f.Close()
		return false, err
	}
	return true, f.Close()
}

// EnsureLists creates missing list files: a provider without
// its file prevents the core from starting
func EnsureLists() {
	for _, p := range []string{paths.ForceDirect(), paths.ForceTunnel(),
		paths.Verified(), paths.ForceDirectApps(), paths.Awg2Hosts()} {
		if _, err := os.Stat(p); err != nil {
			os.WriteFile(p, []byte("# empty\n"), 0o644)
		}
	}
	// second-tunnel presets per settings; the core will not start without the files
	if err := presets.Write(ctl.LoadSettings(paths.Settings()).Awg2Presets); err != nil {
		log.Printf("presets not written: %v", err)
	}
}

// bootstrapDNS: resolvers given by address, not by name. Plain
// UDP/53 is blocked by some ISPs, so the fallback is
// encrypted and by IP as well.
func bootstrapDNS(list []string) []string {
	var out []string
	for _, d := range list {
		r, err := probe.ParseResolver(d)
		if err == nil && net.ParseIP(r.Host) != nil {
			out = append(out, d)
		}
	}
	if len(out) == 0 {
		out = []string{"https://77.88.8.8/dns-query", "tls://77.88.8.1"}
	}
	return out
}
