// Second-tunnel presets: sets of services that always go through awg2,
// bypassing the detector.
//
// The lists were taken from server-side setups solving the same task:
//   - AI: an nginx SNI allow-list plus the Google AI zones;
//   - Telegram: the ranges from core.telegram.org/resources/cidr.txt plus
//     domains;
//   - YouTube: domains (the server relays all of Google via goog.json;
//     the client only needs YouTube).
//
// Every preset is a separate rule-provider with a persistent file. A disabled
// preset is written empty: the core watches the files itself, so enabling or
// disabling needs neither a restart nor a config.yaml change.
package presets

import (
	"bufio"
	"embed"
	"fmt"
	"net"
	"os"
	"strings"

	"dpiswitch/internal/paths"
)

//go:embed lists/*.txt
var lists embed.FS

type Preset struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Note  string `json:"note"`
	files []string
}

var All = []Preset{
	{ID: "youtube", Title: "YouTube", Note: "site, video, thumbnails, apps",
		files: []string{"youtube.txt"}},
	{ID: "telegram", Title: "Telegram", Note: "Telegram domains and networks -- the apps connect by IP",
		files: []string{"telegram-domains.txt", "telegram-cidr.txt"}},
	{ID: "ai", Title: "AI services", Note: "ChatGPT, Claude, Gemini, Grok, Copilot, DeepL and more",
		files: []string{"ai-sni.txt", "ai-google.txt"}},
}

func Valid(id string) bool {
	for _, p := range All {
		if p.ID == id {
			return true
		}
	}
	return false
}

// Rules: classical mihomo rules for a preset.
// domain -> DOMAIN-SUFFIX (covers subdomains), "*.domain" -> suffix as well,
// network -> IP-CIDR/IP-CIDR6 with no-resolve: the rule only fires on
// bare-IP connections and does not force resolving every domain.
func (p Preset) Rules() []string {
	seen := map[string]bool{}
	var out []string
	for _, f := range p.files {
		b, err := lists.ReadFile("lists/" + f)
		if err != nil {
			continue
		}
		sc := bufio.NewScanner(strings.NewReader(string(b)))
		for sc.Scan() {
			l := strings.TrimSpace(sc.Text())
			if l == "" || strings.HasPrefix(l, "#") {
				continue
			}
			var r string
			if _, n, err := net.ParseCIDR(l); err == nil {
				if n.IP.To4() != nil {
					r = "IP-CIDR," + n.String() + ",no-resolve"
				} else {
					r = "IP-CIDR6," + n.String() + ",no-resolve"
				}
			} else {
				r = "DOMAIN-SUFFIX," + strings.ToLower(strings.TrimPrefix(l, "*."))
			}
			if !seen[r] {
				seen[r] = true
				out = append(out, r)
			}
		}
	}
	return out
}

// Write lays presets out into files: enabled ones with rules,
// disabled ones empty.
func Write(enabled []string) error {
	on := map[string]bool{}
	for _, id := range enabled {
		on[id] = true
	}
	for _, p := range All {
		var b strings.Builder
		fmt.Fprintf(&b, "# preset %s -- generated by the program, do not edit\n", p.ID)
		if on[p.ID] {
			for _, r := range p.Rules() {
				b.WriteString(r + "\n")
			}
		} else {
			b.WriteString("# disabled\n")
		}
		path := paths.Preset(p.ID)
		if old, err := os.ReadFile(path); err == nil && string(old) == b.String() {
			continue // avoid needless writes: the core reloads the file on every change
		}
		tmp := path + ".tmp"
		if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
			return err
		}
		if err := os.Rename(tmp, path); err != nil {
			return err
		}
	}
	return nil
}
