package ctl

import (
	"net/netip"
	"os"
	"regexp"
	"slices"
	"strings"

	"dpiswitch/internal/paths"
	"dpiswitch/internal/presets"
)

// The second-tunnel presets reach the core as one rule-provider: the rules
// of every preset switched on, a section to each. A preset switched,
// edited, added or deleted changes that file alone -- the core needs no
// restart and config.yaml no change.

// PresetsProvider: the rule-provider of paths.Presets
const PresetsProvider = "presets"

// presetHead starts a preset's section in the core's file
const presetHead = "# preset "

// PresetRules: a preset's lines as core rules. A site as the lists take it:
// "example.com" that name alone, "+.example.com" the domain and everything
// under it (see nameRule); an address or a network fires only on connections made to it by
// address (no-resolve: it does not make the core resolve every name); a
// program takes all it sends. A line that is none of the kinds is left out,
// as in the user's lists: a hand-edited file cannot break the core's parse.
func PresetRules(p presets.Preset) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, l := range p.Lines {
		if l = strings.TrimSpace(l); l == "" || strings.HasPrefix(l, "#") {
			continue
		}
		kind, v, err := ParseEntry(l)
		if err != nil {
			continue
		}
		var r string
		switch kind {
		case EntryName:
			r = nameRule(v)
		case EntryIP:
			pr, err := netip.ParsePrefix(v)
			if err != nil {
				a := netip.MustParseAddr(v)
				pr = netip.PrefixFrom(a, a.BitLen())
			}
			if pr.Addr().Is4() {
				r = "IP-CIDR," + pr.String() + ",no-resolve"
			} else {
				r = "IP-CIDR6," + pr.String() + ",no-resolve"
			}
		case EntryApp:
			r = "PROCESS-NAME," + v
			if strings.ContainsAny(v, `\/`) {
				r = "PROCESS-PATH," + v
			}
		}
		if !seen[r] {
			seen[r] = true
			out = append(out, r)
		}
	}
	return out
}

// nameRule: the core's rule for a name as the lists write it -- and as the
// core reads it in a list: "x" the name alone, "+.x" x and everything
// under it, ".x" everything under it, "*.x" one level under it. A preset
// is a classical rule-provider, where these are rules of their own; its
// DOMAIN-WILDCARD's * would take dots too, so the last two are regexes.
func nameRule(v string) string {
	switch {
	case strings.HasPrefix(v, "+."):
		return "DOMAIN-SUFFIX," + v[2:]
	case strings.HasPrefix(v, "*."):
		return "DOMAIN-REGEX,^[^.]+" + regexp.QuoteMeta(v[1:]) + "$"
	case strings.HasPrefix(v, "."):
		return "DOMAIN-REGEX,^.+" + regexp.QuoteMeta(v) + "$"
	}
	return "DOMAIN," + v
}

// PresetNameLine: a preset's rule on names as the lists write it -- the
// other way from nameRule; "" for a rule of another kind. What matches a
// connection against the presets reads them this way, as it reads a list.
func PresetNameLine(rule string) string {
	kind, v, ok := strings.Cut(rule, ",")
	if !ok {
		return ""
	}
	v, _, _ = strings.Cut(v, ",")
	switch strings.ToUpper(kind) {
	case "DOMAIN":
		return v
	case "DOMAIN-SUFFIX":
		return "+." + v
	case "DOMAIN-REGEX":
		unq := func(s string) string { return strings.ReplaceAll(s, `\.`, ".") }
		switch {
		case strings.HasPrefix(v, "^[^.]+") && strings.HasSuffix(v, "$"):
			return "*" + unq(strings.TrimSuffix(strings.TrimPrefix(v, "^[^.]+"), "$"))
		case strings.HasPrefix(v, "^.+") && strings.HasSuffix(v, "$"):
			return unq(strings.TrimSuffix(strings.TrimPrefix(v, "^.+"), "$"))
		}
	}
	return ""
}

// presetsBody: the core's file for the presets switched on, a section to
// each: the UI finds a preset's own there (see PresetWritten), whatever
// the others do meanwhile
func presetsBody(all []presets.Preset, enabled []string) []byte {
	on := map[string]bool{}
	for _, id := range enabled {
		on[id] = true
	}
	var b strings.Builder
	b.WriteString("# second-tunnel presets switched on -- generated by the program, do not edit\n")
	for _, p := range all {
		if !on[p.ID] {
			continue
		}
		b.WriteString(presetHead + p.ID + "\n")
		for _, r := range PresetRules(p) {
			b.WriteString(r + "\n")
		}
	}
	return []byte(b.String())
}

// PresetWritten: whether the core's file has a preset as on asks -- its
// rules as they are now when on, nothing of it when off or when the second
// tunnel is not loaded or switched off
func PresetWritten(p presets.Preset, on bool) bool {
	// the second tunnel not loaded or switched off writes none of them
	on = on && LoadSettings(paths.Settings()).Awg2Carries()
	b, err := os.ReadFile(paths.Presets())
	if err != nil {
		return false
	}
	var rules []string
	found, in := false, false
	for _, l := range strings.Split(string(b), "\n") {
		l = strings.TrimSpace(l)
		if id, ok := strings.CutPrefix(l, presetHead); ok {
			in = id == p.ID
			found = found || in
			continue
		}
		if in && l != "" && !strings.HasPrefix(l, "#") {
			rules = append(rules, l)
		}
	}
	if !on {
		return !found
	}
	return found && slices.Equal(rules, PresetRules(p))
}
