package ctl

import (
	"net/netip"
	"os"
	"slices"
	"strings"

	"dpiswitch/internal/paths"
	"dpiswitch/internal/presets"
)

// The second-tunnel presets reach the core as one rule-provider: the rules
// of every preset switched on, a section to each. A preset switched,
// edited, added or deleted changes that file alone -- the core needs no
// restart and config.yaml no change.

// PresetsProvider: the rule-provider of paths.Presets
const PresetsProvider = "presets"

// presetHead starts a preset's section in the core's file
const presetHead = "# preset "

// PresetRules: a preset's lines as core rules. A site takes everything under
// it too; an address or a network fires only on connections made to it by
// address (no-resolve: it does not make the core resolve every name); a
// program takes all it sends. A line that is none of the kinds is left out,
// as in the user's lists: a hand-edited file cannot break the core's parse.
func PresetRules(p presets.Preset) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, l := range p.Lines {
		if l = strings.TrimSpace(l); l == "" || strings.HasPrefix(l, "#") {
			continue
		}
		kind, v, err := ParseEntry(l)
		if err != nil {
			continue
		}
		var r string
		switch kind {
		case EntryName:
			r = "DOMAIN-SUFFIX," + strings.TrimLeft(v, "+.*")
		case EntryIP:
			pr, err := netip.ParsePrefix(v)
			if err != nil {
				a := netip.MustParseAddr(v)
				pr = netip.PrefixFrom(a, a.BitLen())
			}
			if pr.Addr().Is4() {
				r = "IP-CIDR," + pr.String() + ",no-resolve"
			} else {
				r = "IP-CIDR6," + pr.String() + ",no-resolve"
			}
		case EntryApp:
			r = "PROCESS-NAME," + v
			if strings.ContainsAny(v, `\/`) {
				r = "PROCESS-PATH," + v
			}
		}
		if !seen[r] {
			seen[r] = true
			out = append(out, r)
		}
	}
	return out
}

// presetsBody: the core's file for the presets switched on, a section to
// each: the UI finds a preset's own there (see PresetWritten), whatever
// the others do meanwhile
func presetsBody(all []presets.Preset, enabled []string) []byte {
	on := map[string]bool{}
	for _, id := range enabled {
		on[id] = true
	}
	var b strings.Builder
	b.WriteString("# second-tunnel presets switched on -- generated by the program, do not edit\n")
	for _, p := range all {
		if !on[p.ID] {
			continue
		}
		b.WriteString(presetHead + p.ID + "\n")
		for _, r := range PresetRules(p) {
			b.WriteString(r + "\n")
		}
	}
	return []byte(b.String())
}

// PresetWritten: whether the core's file has a preset as on asks -- its
// rules as they are now when on, nothing of it when off
func PresetWritten(p presets.Preset, on bool) bool {
	b, err := os.ReadFile(paths.Presets())
	if err != nil {
		return false
	}
	var rules []string
	found, in := false, false
	for _, l := range strings.Split(string(b), "\n") {
		l = strings.TrimSpace(l)
		if id, ok := strings.CutPrefix(l, presetHead); ok {
			in = id == p.ID
			found = found || in
			continue
		}
		if in && l != "" && !strings.HasPrefix(l, "#") {
			rules = append(rules, l)
		}
	}
	if !on {
		return !found
	}
	return found && slices.Equal(rules, PresetRules(p))
}
