// Application paths. The service runs with C:\Windows\System32 as its working
// directory, so nothing may be resolved relative to the current directory --
// only relative to the actual binary location and to ProgramData.
package paths

import (
	"errors"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

const AppName = "dpiswitch"

// binaries directory: dpiswitch.exe and mihomo.exe sit side by side
func ExeDir() string {
	exe, err := os.Executable()
	if err != nil {
		wd, _ := os.Getwd()
		return wd
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	return filepath.Dir(exe)
}

func Exe() string {
	exe, err := os.Executable()
	if err != nil {
		return filepath.Join(ExeDir(), AppName+".exe")
	}
	return exe
}

func Mihomo() string { return filepath.Join(ExeDir(), "mihomo.exe") }

// data directory on the system drive: does not depend on the binaries'
// volume being ready at boot, and lets the config be locked down by ACL
func DataDir() string {
	base := os.Getenv("ProgramData")
	if base == "" {
		base = `C:\ProgramData`
	}
	return filepath.Join(base, AppName)
}

// EnsureDataDir makes the directories as plain folders, for tests and the
// development UI only: the service makes and locks the real ones itself
// (see SecureDataDir), and nothing running as a user may create them -- a
// folder made by a user is that user's, whatever permissions it is given.
func EnsureDataDir() error {
	for _, d := range []string{DataDir(), LogDir(), UserDir()} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	return nil
}

// UserDir: the one place the user writes. The data directory is the
// service's -- SYSTEM writes there and runs what it holds, so no one else
// may -- and what the user changes (settings, lists, .conf files, a reset)
// lands here, where only the user who installed the service may write.
// The service only reads it, never writes, renames or follows a link in it
// (see ReadUserFile), and copies the lists it takes to the data directory.
func UserDir() string { return filepath.Join(DataDir(), "user") }

// User: a file the user writes, by name
func User(name string) string { return filepath.Join(UserDir(), name) }

// the user's lists: sites, addresses and programs, one per line. The user
// edits the file in UserDir; the core reads the service's copies in the data
// directory, one per kind -- the names under the list's own name, the
// addresses in IPList, the programs in AppList.
const (
	DirectList = "force-direct.txt"
	TunnelList = "force-tunnel.txt"
	BlockList  = "force-block.txt"
	Awg2List   = "awg2-hosts.txt"
	// AppsList: the programs bypassing the tunnel, a user list of its own
	// before the direct list took programs; read until that list is saved
	AppsList = "force-direct-apps.txt"
)

// UserLists: every list the user edits
var UserLists = []string{DirectList, TunnelList, BlockList, Awg2List}

// IPList, AppList: the files of a user list's addresses and programs
func IPList(list string) string  { return strings.TrimSuffix(list, ".txt") + "-ip.txt" }
func AppList(list string) string { return strings.TrimSuffix(list, ".txt") + "-apps.txt" }

// UserReady: whether the user's directory is there to write in -- the
// service makes it when it is installed.
func UserReady() error {
	if fi, err := os.Stat(UserDir()); err != nil || !fi.IsDir() {
		return errNotInstalled
	}
	return nil
}

var errNotInstalled = errors.New("Install the service first: it keeps the settings and lists")

func Settings() string { return User("settings.json") }

func Data(name string) string { return filepath.Join(DataDir(), name) }

func LogDir() string { return filepath.Join(DataDir(), "logs") }

// Config: generated by the service from SourceConf, holds the private keys
func Config() string          { return Data("config.yaml") }
func SourceConf() string      { return User("source.conf") }
func State() string           { return Data("controller-state.json") }
func Reports() string         { return Data("reports.jsonl") }
func Verified() string        { return Data("direct-verified.txt") }
func VerifiedAddr() string    { return Data("direct-verified-addr.txt") }
func VerifiedSplit() string   { return Data("direct-split-verified.txt") }
func ForceDirect() string     { return Data(DirectList) }
func ForceDirectApps() string { return Data(AppList(DirectList)) }
func ForceBlock() string      { return Data(BlockList) }

// ObserveAll: the catch-all the service writes for observe only, see
// ctl.SyncUserFiles
func ObserveAll() string { return Data("observe-all.txt") }

// CoreRun: which run of the core this is -- the service writes it anew
// whenever it starts the core, and the UI's live page starts its history
// over when it changes
func CoreRun() string { return Data("core-run.txt") }

// second tunnel (awg2): source .conf, custom host list, presets -- the
// user's set of them, and the rules of the ones switched on, which the
// service writes for the core
func SourceConf2() string { return User("source2.conf") }
func Awg2Hosts() string   { return Data(Awg2List) }
func UserPresets() string { return User("presets.json") }
func Presets() string     { return Data("presets.txt") }
func ForceTunnel() string { return Data(TunnelList) }
func TunnelIPv6() string  { return Data("tunnel-ipv6.json") }

// DNSCache: the answers the program's DNS cache keeps (see dnscache), and
// what the UI shows of it
func DNSCache() string      { return Data("dns-cache.json") }
func DNSCacheStats() string { return Data("dns-cache-stats.json") }
func ServiceLog() string    { return filepath.Join(LogDir(), "service.log") }
func MihomoLog() string     { return filepath.Join(LogDir(), "mihomo.log") }

// TunnelIPv6Held: when each tunnel was found without IPv6, see
// supervisor.tunnelV6Hold
func TunnelIPv6Held() string { return Data("tunnel-ipv6-held.json") }

// TrayLog: the tray runs as the user and logs in the user's own profile --
// the service's log directory is not the user's to write in
func TrayLog() string {
	dir := os.Getenv("LOCALAPPDATA")
	if dir == "" {
		dir = os.TempDir()
	}
	return filepath.Join(dir, AppName, "tray.log")
}

// UILang: the language last switched to in the UI, for the tray -- the
// user's own, like the tray's log
func UILang() string { return filepath.Join(filepath.Dir(TrayLog()), "lang") }

// ResetRequest: left by the tray to have the service drop every verdict
func ResetRequest() string { return User("reset-verdicts.request") }

// ForgetRequests: what the UI leaves to have the service drop single
// verdicts, a file a request -- the pattern the service looks for
func ForgetRequests() string { return User("forget-*.request") }

// ForgetRequest: a new request's file, a name no other takes
func ForgetRequest() string {
	return User("forget-" + strconv.FormatInt(time.Now().UnixNano(), 10) + ".request")
}
